package:
  name: scrapy-mysql-pipeline
  version:

source:
   git_rev: conda_package
   git_url: https://github.com/phelps-sg/scrapy-mysql-pipeline

requirements:
  build:
    - python
    - setuptools
    - scrapy
    - mysql

  run:
    - python

#test:
#  imports:
#    -

about:
  home: