package:
  name: scrapy-mysql-pipeline
  version:

source:
   git_rev: conda_package
   git_url: https://github.com/phelps-sg/scrapy-mysql-pipeline

requirements:
  build:
    - python=3.8
    - setuptools

  run:
    - python>=3.8
    - scrapy
    - sqlalchemy

#test:
#  imports:
#    -

about:
  home: